// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyd2sOZhasX0j2HYpTTYc2asxq5aoaKk',
    appId: '1:975281618795:web:bc6f7db2dc103038b3962e',
    messagingSenderId: '975281618795',
    projectId: 'todolistphp',
    authDomain: 'todolistphp.firebaseapp.com',
    storageBucket: 'todolistphp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyd2sOZhasX0j2HYpTTYc2asxq5aoaKk',
    appId: '1:975281618795:web:bc6f7db2dc103038b3962e',
    messagingSenderId: '975281618795',
    projectId: 'todolistphp',
    storageBucket: 'todolistphp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyd2sOZhasX0j2HYpTTYc2asxq5aoaKk',
    appId: '1:975281618795:web:bc6f7db2dc103038b3962e',
    messagingSenderId: '975281618795',
    projectId: 'todolistphp',
    storageBucket: 'todolistphp.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMyd2sOZhasX0j2HYpTTYc2asxq5aoaKk',
    appId: '1:975281618795:web:bc6f7db2dc103038b3962e',
    messagingSenderId: '975281618795',
    projectId: 'todolistphp',
    storageBucket: 'todolistphp.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyd2sOZhasX0j2HYpTTYc2asxq5aoaKk',
    appId: '1:975281618795:web:bc6f7db2dc103038b3962e',
    messagingSenderId: '975281618795',
    projectId: 'todolistphp',
    authDomain: 'todolistphp.firebaseapp.com',
    storageBucket: 'todolistphp.firebasestorage.app',
  );
}
